export default [
  {
    'id': 1,
    'restaurantID': 1,
    'stars': 5,
    'uploadDate': '2020-04-02T07:00:00.000Z',
    'restaurantVisit': 1,
    'content': 'It was delicious!',
    'emojiUseful': 1,
    'emojiFunny': null,
    'emojiCool': null,
    'reply': 'I\'m glad you enjoyed it!',
    'userID': 1
  },
  {
    'id': 2,
    'restaurantID': 1,
    'stars': 2,
    'uploadDate': '2020-03-23T07:00:00.000Z',
    'restaurantVisit': null,
    'content': 'Wasn\'t great',
    'emojiUseful': 1,
    'emojiFunny': 1,
    'emojiCool': null,
    'reply': null,
    'userID': 2
  },
  {
    'id': 3,
    'restaurantID': 2,
    'stars': 4,
    'uploadDate': '2020-02-12T08:00:00.000Z',
    'restaurantVisit': 2,
    'content': 'Love this place',
    'emojiUseful': 1,
    'emojiFunny': null,
    'emojiCool': 1,
    'reply': 'Thank you!',
    'userID': 3
  },
  {
    'id': 4,
    'restaurantID': 3,
    'stars': 5,
    'uploadDate': '2020-01-10T08:00:00.000Z',
    'restaurantVisit': null,
    'content': 'Best Naan in town',
    'emojiUseful': 1,
    'emojiFunny': 1,
    'emojiCool': 1,
    'reply': null,
    'userID': 4
  },
  {
    'id': 5,
    'restaurantID': 4,
    'stars': 5,
    'uploadDate': '2020-03-25T07:00:00.000Z',
    'restaurantVisit': null,
    'content': 'Try their springrolls',
    'emojiUseful': 1,
    'emojiFunny': null,
    'emojiCool': null,
    'reply': null,
    'userID': 5
  },
  {
    'id': 6,
    'restaurantID': 3,
    'stars': 4,
    'uploadDate': '2020-01-10T08:00:00.000Z',
    'restaurantVisit': 1,
    'content': 'Lamb curry was my favorite',
    'emojiUseful': 1,
    'emojiFunny': null,
    'emojiCool': null,
    'reply': null,
    'userID': 3
  },
  {
    'id': 7,
    'restaurantID': 2,
    'stars': 3,
    'uploadDate': '2020-05-01T07:00:00.000Z',
    'restaurantVisit': null,
    'content': 'Too spicy',
    'emojiUseful': null,
    'emojiFunny': null,
    'emojiCool': null,
    'reply': null,
    'userID': 5
  }
]